"""
State management for the Data Analysis LangGraph Agent.
Defines the state structure and types for the analysis workflow.
"""

from typing import TypedDict, List, Dict, Any, Optional
import pandas as pd
from dataclasses import dataclass, field
from enum import Enum
from langchain_core.messages import BaseMessage

@dataclass
class QueryResult:
    """Container for query execution results."""
    query: str
    dataframe: pd.DataFrame
    execution_time: float
    row_count: int

class AnalysisType(Enum):
    """Types of analysis the agent can perform."""
    CUSTOMER_SEGMENTATION = "customer_segmentation"
    CUSTOMER_BEHAVIOR = "customer_behavior"
    PRODUCT_PERFORMANCE = "product_performance"
    PRODUCT_RECOMMENDATIONS = "product_recommendations"
    SALES_TRENDS = "sales_trends"
    SALES_SEASONALITY = "sales_seasonality"
    GEOGRAPHIC_PATTERNS = "geographic_patterns"
    GENERAL_INSIGHTS = "general_insights"

@dataclass
class AnalysisContext:
    """Context information for the current analysis."""
    analysis_type: AnalysisType
    parameters: Dict[str, Any] = field(default_factory=dict)
    table_names: List[str] = field(default_factory=list)
    time_range: Optional[Dict[str, str]] = None
    filters: Dict[str, Any] = field(default_factory=dict)

@dataclass
class Insight:
    """Individual insight generated by the agent."""
    content: str
    confidence: float = 1.0
    data_source: str = ""
    analysis_type: AnalysisType = AnalysisType.GENERAL_INSIGHTS
    supporting_data: Optional[Dict[str, Any]] = None

class AnalysisState(TypedDict, total=False):
    """
    Complete state for the data analysis LangGraph agent workflow.

    This TypedDict defines all possible state keys that can exist during
    the agent's execution. Updated to work with LangGraph's state system.
    """

    # Conversation management (now uses LangGraph messages)
    messages: List[BaseMessage]
    """History of user messages and assistant responses using LangGraph message system"""

    # Current analysis context
    current_analysis: Optional[AnalysisType]
    """Type of analysis currently being performed"""

    analysis_context: Optional[AnalysisContext]
    """Detailed context for the current analysis"""

    # Query execution tracking
    current_query: Optional[QueryResult]
    """Currently executing or most recent query"""

    query_history: List[QueryResult]
    """History of all queries executed in this session"""

    # Analysis results
    insights: List[Insight]
    """Generated insights from the analysis"""

    raw_dataframes: Dict[str, pd.DataFrame]
    """Raw dataframes from query results for further processing"""

    # Error handling
    errors: List[str]
    """List of errors encountered during execution"""

    last_error: Optional[str]
    """Most recent error message"""

    # Session management
    session_id: str
    """Unique identifier for this analysis session"""

    created_at: str
    """Timestamp when the session was created"""

    # Configuration
    max_insights: int
    """Maximum number of insights to generate"""

    enable_llm_insights: bool
    """Whether to use LLM for generating natural language insights"""

def determine_analysis_type(user_input: str) -> AnalysisType:
    """
    Determine the type of analysis requested based on user input.

    This function uses simple keyword matching to categorize user requests.
    In a production system, this could be enhanced with NLP or LLM classification.
    """

    input_lower = user_input.lower()

    # Customer analysis keywords
    if any(keyword in input_lower for keyword in ["customer", "user", "segment", "behavior", "demographic"]):
        if "segment" in input_lower:
            return AnalysisType.CUSTOMER_SEGMENTATION
        else:
            return AnalysisType.CUSTOMER_BEHAVIOR

    # Product analysis keywords
    elif any(keyword in input_lower for keyword in ["product", "item", "recommend", "performance", "popular"]):
        if "recommend" in input_lower:
            return AnalysisType.PRODUCT_RECOMMENDATIONS
        else:
            return AnalysisType.PRODUCT_PERFORMANCE

    # Sales analysis keywords
    elif any(keyword in input_lower for keyword in ["sales", "revenue", "trend", "seasonal", "growth"]):
        if "seasonal" in input_lower or "trend" in input_lower:
            return AnalysisType.SALES_TRENDS
        else:
            return AnalysisType.SALES_SEASONALITY

    # Geographic analysis keywords
    elif any(keyword in input_lower for keyword in ["geographic", "location", "region", "state", "country", "city"]):
        return AnalysisType.GEOGRAPHIC_PATTERNS

    # Default to general insights
    return AnalysisType.GENERAL_INSIGHTS